# Generated by Django 4.0.5 on 2022-09-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focrbe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dectection',
            new_name='Detection',
        ),
    ]
