# Generated by Django 4.1 on 2022-09-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focrbe', '0002_rename_dectection_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChungMinhNhanDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soCmnd', models.TextField()),
                ('hoVaTen', models.TextField()),
                ('ngaySinh', models.TextField()),
                ('noiSinh', models.TextField()),
                ('gioiTinh', models.TextField()),
                ('ngayCap', models.TextField()),
                ('noiCap', models.TextField()),
            ],
        ),
    ]
