# Generated by Django 4.1 on 2022-09-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focrbe', '0003_chungminhnhandan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chungminhnhandan',
            old_name='gioiTinh',
            new_name='nguyenQuan',
        ),
        migrations.RenameField(
            model_name='chungminhnhandan',
            old_name='ngayCap',
            new_name='noiDktt',
        ),
        migrations.RemoveField(
            model_name='chungminhnhandan',
            name='noiCap',
        ),
        migrations.RemoveField(
            model_name='chungminhnhandan',
            name='noiSinh',
        ),
    ]
