# Generated by Django 4.1 on 2022-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focrbe', '0004_rename_gioitinh_chungminhnhandan_nguyenquan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chungminhnhandan',
            name='imagePath',
            field=models.TextField(default=''),
        ),
    ]
